### ISSUE TITLE
Synchronize artifact version number and source version number

### ISSUE THREAD

**Issue by stelfrich** [fiji/Auto_Threshold#11]
The version number of this artifact is out of sync with hard-coded ones in the source code:
- POM says [1.17.1-SNAPSHOT](https://github.com/fiji/Auto_Threshold/blob/master/pom.xml#L14) 
- `Auto_Local_Threshold.java` says [1.10](https://github.com/fiji/Auto_Threshold/blob/master/src/main/java/fiji/threshold/Auto_Local_Threshold.java#L34)
- `Auto_Threshold.java` says [1.17](https://github.com/fiji/Auto_Threshold/blob/master/src/main/java/fiji/threshold/Auto_Threshold.java#L42-L45)

I propose to bump both versions in the sources to the same version as the POM (without the `SNAPSHOT` suffix), i.e. `1.17.1` and cut a new release. Subsequently, version numbers should be bumped in sync with the POM (to minimize confusion).

**Comment by landinig** [comment]
Auto threshold is one plugin, Auto local threshold is a different one. They are completely independent, no need to change any version numbers.

**Comment by ctrueden** [comment]
@landinig The SciJava scheme is "one JAR, one version." If you want these two plugins to have separate versions, then they should live in separate JARs (and separate Git repositories). Currently, since they are in one JAR, they have one version. And that version is `1.17.1-SNAPSHOT`, leading up to `1.17.1` final release. The versions encoded in the source should not be considered valid—it is too easy to accidentally introduce two different artifacts purporting to be the same version that way.

If you would like to split `Auto_Local_Threshold` to its own JAR/repo so that it can be versioned separately, let me know. We could then make the `pom.xml`s indicate the correct respective versions.

Some related documentation is [here](https://imagej.net/Fiji/Contribution_requirements#Versioning_and_dependency_convergence) and [here](https://imagej.net/Architecture#Git_repositories) if you have time and interest.

**Comment by landinig** [comment]
Updating a version when no code has changed does not sound particularly useful either.
This seems to stem from just packing the two plugins in one jar file (not something that I chose to do).
I think it would be better if these two plugins are removed from the default Fiji distribution and instead I provide both plugins via my Morphology update site (or I create a new AutoThreshold update site).
I always provide the source code in the jar, so nothing is really lost. 
That would enable me to provide updates quicker (as I could update them earlier than the Fiji releases) and would be less of a hassle as I do not find git easy to use (and I always end asking asking somebody else for help).

**Comment by ctrueden** [comment]
> This seems to stem from just packing the two plugins in one jar file (not something that I chose to do).

As I said, I am happy to split them each to their own separately versioned JAR file, if you wish! No problem at all.

> I think it would be better if these two plugins are removed from the default Fiji distribution ... I always provide the source code in the jar, so nothing is really lost.

It is your call, but you will lose several things:

* The "Source" action button of the new ImageJ search bar works by inspecting the containing JAR file of the plugin, looking in the embedded `pom.xml` for the `<scm>` tag. It understands code from GitHub, such that when the "Source" button is clicked, a browser window opens to display the source to the user. Bundling your source differently would either: A) make this button not work anymore for your plugins; or B) necessitate extending the heuristic to handle additional edge cases such as the source being bundled in the JAR file.

* Each component JAR file has a wiki page with an autogenerated template listing important metadata about the project, such as who the maintainers are, at what level(s) the plugin is supported, what the project license is, when the last release was, etc. For example, the Auto Threshold page is [here](https://imagej.net/Auto_Threshold).

* Component JAR files are deployed to the ImageJ Maven repository, such that other components may depend on your component. I scanned plugins known to me, and none of them currently depend on `sc.fiji:Auto_Threshold`, so you won't be hanging anyone out to try by ceasing to publish your plugins to the Maven repository. But be aware that it would preclude anyone from easily depending on the plugins in the future.

> That would enable me to provide updates quicker

I apologize that turnaround time has been slow lately. If this issue is your main concern, I can prioritize improving the speed of Fiji updates. Two main things needed there: 1) automatically testing new component releases against the entire Fiji distribution, to be confident plugin B still works when plugin A is updated; and 2) automatically uploading those new component releases once that automatic testing confirms it is safe. This machinery has been planned for a while, but the status quo has been "good enough" that I didn't prioritize working on it yet.

On the other hand, moving all your stuff to the Morphology update site would indeed give you complete control, with a very rapid deployment mechanism. But it also puts you in danger of Fiji "pulling the rug out from under you" with a core ImageJ or Fiji update that breaks your stuff, and no automated testing in place to protect you from that.

**Comment by ctrueden** [comment]
I split the repositories:

* https://github.com/fiji/Auto_Threshold (this repository)
* https://github.com/fiji/Auto_Local_Threshold

I released Auto_Local_Threshold 1.10.0, and also released Auto_Threshold version 1.17.1 (same as 1.17.0 but Auto_Local_Threshold now removed).

And I added Auto_Local_Threshold to the SciJava component collection (scijava/pom-scijava@eef885ac3a2a2eb36e13376c2bda73b1334d5336).

And I uploaded the two above releases to the Java-8 update site. So users should now have all the new fixes.

**Comment by ctrueden** [comment]
One thing I forgot before releasing: the `Auto_Local_Threshold.java` still hardcoded `v1.10`. So I have changed it to extract the version from the POM now: fiji/Auto_Local_Threshold@d743a730e70b6cb12ba08fc781c313bfe2e95a09.

**Comment by landinig** [comment]
Thank you @ctrueden. Just to clarify, when introducing new edits to these files, does one need to edit the POM file or is this done by a script?

**Comment by ctrueden** [comment]
@landinig Sorry this sat unanswered for so long.

Regarding editing the POM: there is [a script for cutting releases](https://imagej.net/Development_Lifecycle#Phase_3:_Released) that creates the final `x.y.z` for a given `x.y.z-SNAPSHOT` on the master branch, and then bumps to `x.y.<z+1>` by default.

Sometimes, it is desirable to instead release `x.<y+1>.0` or even `<x+1>.0.0` as dictated by the [Semantic Versioning](https://imagej.net/Versioning) scheme that [most Fiji components use](https://imagej.net/Fiji/Contribution_requirements#Versioning_and_dependency_convergence). In this situation, I sometimes manually update the POM from `x.y.z-SNAPSHOT` to `x.<y+1>.0-SNAPSHOT` (or `<x+1>.0.0-SNAPSHOT`) to signify my future intent to do this.
